config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/aboutme'
  get 'static_pages/photos'

  get 'sessions/new'

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  get    'admin'   => 'sessions#new'
  post   'admin'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get '/overmij' => 'static_pages#aboutme'
  get '/fotos' => 'static_pages#photos'

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates_presence_of :body, :name
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments

	validates_presence_of :body, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		
		if @comment.save
  			respond_to do |format|
				format.html { redirect_to @post }
				format.js
			end
		else
			respond_to do |format|
				format.html { redirect_to @post, notice: 'Geef een naam en reactie' }
				format.js
			end
 		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = Comment.find(params[:id])
		@comment.destroy

		respond_to do |format|
			format.html { redirect_to @post }
			format.js
		end
	end

	private

	def comment_params
	    params.require(:comment).permit(:name, :body)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include SessionsHelper
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    if logged_in?
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if logged_in?
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if logged_in?
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :images)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
  end

  def create
    if params[:session][:username] == ENV['USERNAME'] && params[:session][:password] == ENV['PASSWORD']
      log_in
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
  	log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def aboutme
  end

  def photos
  	@posts = Post.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in
    	session[:user_id] = "admin"
  	end

  	def current_user
    	@current_user ||= session[:user_id]
  	end

  	def logged_in?
    	!current_user.nil?
  	end

  	def log_out
    	session.delete(:user_id)
    	@current_user = nil
  	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <p>
    <strong>
      Posted <%= time_ago_in_words(comment.created_at) %> ago
    </strong>
    <br/>
    <i><%= comment.name %>:</i>
    <%= comment.body %>
  </p>
  <p>
    <% if logged_in? %>
  	  <%= button_to 'Delete', [comment.post, comment],
               :method => :delete,
               :class => 'link-button',
               remote: true,
               data: { confirm: 'Are you sure?' }
               %>
    <% end %>

  </p>
<% end %>

app/views/comments/create.js.erb
$('#comments').prepend('<%= escape_javascript(render partial: @comment) %>');
$('#comment_name').val('')
$('#comment_body').val('')

app/views/comments/destroy.js.erb
$('#comments').html('<%= escape_javascript(render partial: @post.comments) %>');

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Powered by: <%= link_to 'rails-3-2-intro-blog', 'https://github.com/reinteractive-open/rails-3-2-intro-blog' %>
    Developed at: <%= link_to 'InstallFest 2013', 'http://reinteractive.net/service/installfest' %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<nav class="header">
  <h1 id="title">
    <%= link_to 'Tessa in Hatfield', root_path %>
  </h1>
  <section>
    <ul id="menu">
      <li class="menu-item">
        <%= link_to 'Foto\'s', '/fotos' %> | 
      </li>
      <li class="menu-item">
        <%= link_to 'Over mij', '/overmij' %>
      </li>
    </ul>
  </section>
  <% if logged_in? %>
    <%= button_to "Log out", logout_path, method: :delete, :id => 'logout-button', :class => 'link-button' %>
  <% end %>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tessa in Hatfield</title>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <meta name=viewport content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
  <%= render partial: 'layouts/header' %>

<div id="main">
  	<% flash.each do |message_type, message| %>
    	<div class="flash"><%= message %></div>
  <% end %>

  <%= yield %>
</div>
  <%= render partial: 'layouts/footer' %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</p>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-thing">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="input-thing">
    <%= f.label :images %><br>
    <%= f.text_field :images %>
  </div>
  <div class="input-thing">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="input-thing">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
 <h2><%= link_to_unless_current post.title, post %></h2>
 
<% unless post.images.nil? or post.images.empty? %>	
 	<div class="post-images">
	 	<% images = post.images.split(" ") %>
	 	<% images.each do |image| %>
	 		<%= image_tag(image) %>
	 	<% end %>
	  </div>
<% end %>

<%= simple_format post.body %>

app/views/posts/_posttease.html.erb
 <h2><%= link_to_unless_current posttease.title, posttease %></h2>
 <% if posttease.body.length < 300 %>
 	<%= simple_format truncate(sanitize(posttease.body), length: posttease.body.length - 1, separator: ' ', omission: '... ') { link_to "Lees verder", posttease }%>
 <% else %>
 	<%= simple_format truncate(sanitize(posttease.body), length: 300, separator: ' ', omission: '... ') { link_to "Lees verder", posttease }%>
 <% end %>

app/views/posts/edit.html.erb
<section class="yellow">
	<h2>Editing post</h2>

	<%= render 'form' %>

	<%= link_to 'Show', @post %> |
	<%= link_to 'Back', posts_path %>
</section>

app/views/posts/index.html.erb
<div id="main-img"></div>

<section id="post-section">
	<%= render partial: "posttease", collection: @posts %>

	<% if logged_in? %>
	  <%= link_to 'New Post', new_post_path %>
	<% end %>
</section>

app/views/posts/new.html.erb
<section class="yellow">
	<h2>New post</h2>

	<%= render 'form' %>

	<%= link_to 'Back', posts_path %>
</section>

app/views/posts/show.html.erb
<section id="post-section">
  <%= render partial: @post %>
  <% if logged_in? %>
    <div class="link-block">
      <%= button_to 'Delete', post_path,
                     :method => :delete,
                     data: { confirm: 'Are you sure?' },
                     :class => 'link-button'
                     %> |
      <%= link_to 'Edit', edit_post_path(@post) %> |
      <%= link_to 'Back', posts_path %>
    </div>
  <% else %>
    <%= link_to 'Terug', posts_path %>
  <% end %>
</section>

<section id="comment-section">
  <h2>Reacties</h2>
  <div id="comments">
  	<%= render partial: @post.comments.reverse %>
  </div>
    
  <%= form_for [@post, Comment.new], remote: true, authenticity_token: true do |f| %>
    <p>
      <%= f.label :name, "Naam" %><br/>
      <%= f.text_field :name %></br></br>

      <%= f.label :body, "Reactie" %><br/>
      <%= f.text_area :body %>
    </p>
    <p><%= f.submit "Verstuur" %></p>
  <% end %>
</section>

app/views/static_pages/aboutme.html.erb
<div class="yellow">
	<h2>Over mij</h2>
	<p>Ik studeer een semester aan de University of Hertfordshire, Hatfield, Groot-Brittannië.</p>
</div>

app/views/static_pages/photos.html.erb
<div class="yellow">
	<h2>Foto's</h2>
		
 	<div class="all-images">
 		<% @posts.each do |post| %>
 			<% unless post.images.nil? %>
				<% images = post.images.split(" ") %>
		 		<% images.each do |image| %>
		 			<%= image_tag(image) %>
		 		<% end %>
		 	<% end %>
		<% end %>
    </div>
</div>